/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SteamKeyService } from "../steamKey.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SteamKeyCreateInput } from "./SteamKeyCreateInput";
import { SteamKey } from "./SteamKey";
import { SteamKeyFindManyArgs } from "./SteamKeyFindManyArgs";
import { SteamKeyWhereUniqueInput } from "./SteamKeyWhereUniqueInput";
import { SteamKeyUpdateInput } from "./SteamKeyUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SteamKeyControllerBase {
  constructor(
    protected readonly service: SteamKeyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SteamKey })
  @nestAccessControl.UseRoles({
    resource: "SteamKey",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSteamKey(
    @common.Body() data: SteamKeyCreateInput
  ): Promise<SteamKey> {
    return await this.service.createSteamKey({
      data: {
        ...data,

        order: data.order
          ? {
              connect: data.order,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        activated: true,
        createdAt: true,
        expiryDate: true,
        gameName: true,
        id: true,
        key: true,

        order: {
          select: {
            id: true,
          },
        },

        price: true,
        releaseDate: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SteamKey] })
  @ApiNestedQuery(SteamKeyFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SteamKey",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async steamKeys(@common.Req() request: Request): Promise<SteamKey[]> {
    const args = plainToClass(SteamKeyFindManyArgs, request.query);
    return this.service.steamKeys({
      ...args,
      select: {
        activated: true,
        createdAt: true,
        expiryDate: true,
        gameName: true,
        id: true,
        key: true,

        order: {
          select: {
            id: true,
          },
        },

        price: true,
        releaseDate: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SteamKey })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SteamKey",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async steamKey(
    @common.Param() params: SteamKeyWhereUniqueInput
  ): Promise<SteamKey | null> {
    const result = await this.service.steamKey({
      where: params,
      select: {
        activated: true,
        createdAt: true,
        expiryDate: true,
        gameName: true,
        id: true,
        key: true,

        order: {
          select: {
            id: true,
          },
        },

        price: true,
        releaseDate: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SteamKey })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SteamKey",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSteamKey(
    @common.Param() params: SteamKeyWhereUniqueInput,
    @common.Body() data: SteamKeyUpdateInput
  ): Promise<SteamKey | null> {
    try {
      return await this.service.updateSteamKey({
        where: params,
        data: {
          ...data,

          order: data.order
            ? {
                connect: data.order,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          activated: true,
          createdAt: true,
          expiryDate: true,
          gameName: true,
          id: true,
          key: true,

          order: {
            select: {
              id: true,
            },
          },

          price: true,
          releaseDate: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SteamKey })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SteamKey",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSteamKey(
    @common.Param() params: SteamKeyWhereUniqueInput
  ): Promise<SteamKey | null> {
    try {
      return await this.service.deleteSteamKey({
        where: params,
        select: {
          activated: true,
          createdAt: true,
          expiryDate: true,
          gameName: true,
          id: true,
          key: true,

          order: {
            select: {
              id: true,
            },
          },

          price: true,
          releaseDate: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
